/*
 * ConfigDefines.h
 *
 *  Created on: Apr 19, 2018
 *      Author: drue
 */

#ifndef ROVEBOARD_TM4C1294NCPDT_API_ROVEETHERNET_CONFIGDEFINES_H_
#define ROVEBOARD_TM4C1294NCPDT_API_ROVEETHERNET_CONFIGDEFINES_H_

const char MAX_CLIENTS = 3;



#endif /* ROVEBOARD_TM4C1294NCPDT_API_ROVEETHERNET_CONFIGDEFINES_H_ */
